version: '3.8'

services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: network_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    image: node:18-alpine
    restart: always
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "9002:9002"
    environment:
      DATABASE_URL: "postgresql://admin:password@db:5432/network_db?schema=public"
    depends_on:
      - db
    command: sh -c "npm install && npm run dev"

volumes:
  db_data:
