version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: network_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    image: node:latest
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3001:3001"
    depends_on:
      - db

volumes:
  db_data: